### PR TITLE
crypto: Show exponent in decimal and hex

### LINKED ISSUE #17202: TLS Peer certificate exponent listed as "10001"
The exponent should probably be stored in the peer certificate object as the number `65537` instead of the binary`10001` (unless there's a reason for the binary representation).

### PR DESCRIPTION
**Pull request by iamthechad**
Show the exponent in a manner that matches OpenSSL
Fixes #17202

### CODE REVIEW

**Comment by jasnell** [comment]
Definitely can appreciate the intent on this, but it does involve a bit of an API change, which we should likely avoid in v0.12 and v0.10. This should likely be targeted at http://github.com/nodejs/io.js or http://github.com/nodejs/node instead.

**Comment by iamthechad** [comment]
I'll admit I don't know much about the timelines around which repo to use when. Are future changes not going to be applied to this repo any more? We knew this was a breaking change, which is why it's targeted at `master` and not a specific release.

**Comment by jasnell** [comment]
For breaking changes, we want to target `nodejs/io.js` or `nodejs/node` as that is where the next major release will come from. `joyent/node` is largely intended for LTS of the `v0.12` and `v.10` streams.

**Comment by iamthechad** [comment]
Okay. Is there a preference as to which repo - `nodejs/iojs` vs `nodejs/node`?

**Comment by jasnell** [comment]
Likely io.js would be best.

**Comment by iamthechad** [comment]
Resubmitted to `io.js`. Should this PR be closed?

**Comment by jasnell** [comment]
Yes, thank you!

**Pull request closed without merging**
