### PR TITLE
OpenSSL upgrade to 1.0.1l

### PR DESCRIPTION
**Pull request by misterdjules**
This PR is similar to #9056 with the following differences:
- It splits the commits differently (it extracts the fix to `test-crypto-stream.js` in a separate commit).
- It includes the fix to the 64 bits Windows build.

Tests pass [on Windows](http://jenkins.nodejs.org/job/node-review-windows-julien/) and on [other supported platforms](http://jenkins.nodejs.org/job/node-review-unix-julien/)

### CODE REVIEW

**Comment by jasnell** [comment]
+1. LGTM.

**Comment by cjihrig** [comment]
Rubber stamp LGTM

**Comment by misterdjules** [comment]
Thank you, landed in b28c76e9d265d42934adc7833c77f57c1d80d6eb, deef605085be2dcd76bd2538ec32691e60a5e362, f5e9b6e84a47a6990bd3b44d004026a6f0faaba2 and 9e387fb611e29aad3118e0b226199fdc70bbd0cd.

**Comment by jasnell** [comment]
woot! thanks all

**Pull request closed without merging**
