### PR TITLE
cluster: introduce `distribute` option

### LINKED ISSUE #6001: cluster: implement API for pluggable distribute() for round-robin scheduler
Looks usefull to provide API in the cluster module to define user own [`distribute`](https://github.com/joyent/node/blob/22c68fdc1dae40f0ed9c71a02f66e5b2c6353691/lib/cluster.js#L161) method.

Something like following:

``` javascript
cluster.setupMaster({
  schedulingPolicy: cluster.SCHED_RR,
  distributeRequest: function() {
    // ...
    return worker;
  }
});
```

Previous discussion with @bnoordhuis in the issue #4435 (after closing)

### PR DESCRIPTION
**Pull request by indutny**
`distribute` is a user-specified callback for asynchronous balancing of
incoming connections to cluster workers.

fix #6001

/cc @bnoordhuis @isaacs @kaero

### CODE REVIEW

**Comment by jasnell** [comment]
@indutny ... any further progress on this one? Is this still needed?

**Comment by indutny** [comment]
cc @kaero ?

**Comment by kaero** [comment]
Requests distribution problem is still here, but for a long time we successfully use dual-layer load balancing. RR at proxy level (nginx/haproxy/...) is used to distribute requests between small groups of workers and on node.js level, we just use default behavior – it works fine.
Dynamic RR between single node.js workers at proxy level is works well too.
So maybe it's not a node.js problem, to provide such a method.  `¯\_(ツ)_/¯`

**Comment by jasnell** [comment]
Ok. With that in mind then, I'm going to close this. We can revisit if anything thinks having this in core is necessary.

**Pull request closed without merging**
