### PR TITLE
build: work around VS2015 issue in ICU <56 (master)

### LINKED ISSUE #25792: build: VS2015 failure (ICU) back port from io.js
https://github.com/nodejs/io.js/issues/2279 will affect 0.12+ as well under VS2015 with `Intl` on.

Basically, VS2015 broke ICU. We'll fix it in ICU 56.

It should apply cleanly, but I couldn't get VS2015 to build with `joyent/node/master`.

I will open a PR anyway, but will need some help testing.

NB this also adds a general mechanism for floating patches on top of ICU.
@orangemocha

### PR DESCRIPTION
**Pull request by srl295**
probably fixes #25792

Also, adds general mechanism for floating patches on top of ICU.

The particular ufile.c is from
 http://bugs.icu-project.org/trac/changeset/37704
and should be OK for ICU 54 and 55.

backport from: https://github.com/nodejs/io.js/pull/2283

### CODE REVIEW

**Comment by srl295** [comment]
@orangemocha I couldn't get this to build against VS2015 , it said "setting up environment for VS2010…".  So, this is *not tested* sorry. But the mechanism works as merged, I just can't cleanly test it yet.

**Comment by srl295** [comment]
@mhdawson @jasnell also FYI

**Comment by orangemocha** [comment]
Pending review at https://github.com/nodejs/io.js/pull/2283 and testing.

This should go into v0.12 though, not master, right?

**Comment by srl295** [comment]
@orangemocha good question. It needs to go anywhere that wants to build against vs2015 - what do you advise?

**Comment by orangemocha** [comment]
@srl295 then it should go first in the oldest LTS version that has ICU support. Assuming icu is not supported in v0.10, this change should go into v0.12. Thanks!

**Comment by srl295** [comment]
@orangemocha Sounds good. OK, I will close this PR and reopen against v0.12

**Pull request closed without merging**
