### PR TITLE
deps: updated libuv to 1.2.1

### LINKED ISSUE #8988: node-fastcgi compatibility with node ≥ 0.11.8
I've filed this bug on [node-fastcgi](https://github.com/fbbdev/node-fastcgi/issues/2) bug tracker also. I think it could be a more general compatibility issue for next release of node so I am reporting it here also:

First have a look at node-fastcgi and the bug I've filed [there](https://github.com/fbbdev/node-fastcgi/issues/2). Here is my configurations:

.lighttpd.conf:
```conf
server.document-root = "."
server.modules += ( "mod_fastcgi" )
server.port = 2020
fastcgi.server += (
  "/myapp" => ((
    "socket" => "/tmp/myapp-fcgi.sock",
    "bin-path" => "/home/user/myapp/server.js",
    "check-local" => "disable",
    "max-procs" => 1,
  ))
)
```

[server.js](https://github.com/fbbdev/node-fastcgi#example):
```JavaScript
#!/home/user/.nvm/v0.11.8/bin/node

var fcgi = require('node-fastcgi');

fcgi.createServer(function(req, res) {
  if (req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end("It's working");
  } else {
    res.writeHead(501);
    res.end();
  }
}).listen();
```

Do `chmod +x server.js` and `npm install node-fastcgi` then `lighttpd -f .lighttpd.conf -D` and open http://127.0.0.1:2020/myapp on your browser. It works if you install 0.11.7 and change server.js to use it but for 0.11.8 and newer node versions, it just makes browser waiting forever and does nothing.

### PR DESCRIPTION
**Pull request by saghul**
We made quite some bugfixes and uv_try_write got implemented on Windows, which improves the writes performance. API is backwards compatible and ABI hasn't changed.

R=@tjfontaine, @cjihrig

This should close #8988

### CODE REVIEW

**Comment by saghul** [comment]
Oh, tests do pass locally (Linux), I hope Jenkins agrees :-)

**Comment by cjihrig** [comment]
Rubber stamp LGTM. Let's see what Jenkins says.

**Comment by cjihrig** [comment]
Oh, and @tjfontaine does this need to wait or can it go in 0.12?

**Comment by misterdjules** [comment]
In my opinion, we should land that post 0.11.15 now that we closed all outstanding issues/PRs in this milestone and the build is all green.

**Comment by saghul** [comment]
Gentle reminder, now that 0.11.15 is out :-)

**Comment by tjfontaine** [comment]
We're pretty long in the tooth in the process towards releasing v0.12 -- upgrading libuv at this point is too much change before we release. I would prefer we push this to master.

**Comment by saghul** [comment]
@tjfontaine While I understand, don't let the version number deceive you, it's not a major upgrade. We now follow semver so we had to bump the minor twice because a couple of new (small) features where added.

FWIW, iojs has run all releases since 1.0 and thanks to that we were able to fix a couple of regressions like #8988. If you ship Node with 1.0 #8988 is broken.

**Comment by misterdjules** [comment]
Adding it to the 0.12.1 milestone, even though a more recent version of libuv than 1.2.1 might be preferable at that time. Thank you @saghul for your help and support.

**Comment by saghul** [comment]
@misterdjules no worries. I'll update this PR with 1.3.0 in the upcoming days.

**Comment by saghul** [comment]
I opened a new PR here: https://github.com/joyent/node/pull/9165 since I cannot the change the title of this one, and it would be misleading.

**Comment by misterdjules** [comment]
Cleared the 0.12.1 milestone since it never landed and has been superseded by https://github.com/joyent/node/pull/9179.

**Pull request closed without merging**
