### PR TITLE
add CLI option to syntax check script, fixes #9426

### LINKED ISSUE #9426: command line switch to syntax check javascript
It would be nice to be able to pass a flag to `node` that would tell it to just syntax check, and not execute, the given script.

With ruby you can run `ruby -c file.rb` and bash `bash -n file.sh` which both result in just a syntax check without any code execution.  Both work in a similar fashion where proper syntax will result in no output with an exit code of 0, whereas improper syntax will generate debug information on stderr and an exit code of non-0.

We (job) currently use the following as a pre-commit git hook to syntax check json, ruby, bash, and javascript.  Even though `vm` is a stability level of 3, it still could change in the future which could break this functionality. Having a single command line switch to do effectively what is done in `check_js` would be extremely convenient and useful.

``` js
check_json() {
	debug 'checking JSON syntax'
	json < "$1" > /dev/null
}

check_ruby() {
	debug 'checking ruby syntax'
	ruby -c "$1" > /dev/null
}

check_bash() {
	debug 'checking bash syntax'
	bash -n "$1" > /dev/null
}

check_js() {
	debug 'checking javascript syntax'
	node -e '
	var vm = require("vm");
	var fs = require("fs");
	var source = fs.readFileSync(process.argv[1], "utf8").replace(/^#.*/, "");
	new vm.Script(source, {displayErrors: true});
	' "$1"
}
```

### PR DESCRIPTION
**Pull request by bahamas10**
discussion in https://github.com/joyent/node/issues/9426

This is my first contribution to node core so I may have missed a few files when trying to add this functionality... but in my testing everything worked as expected.

```
$ cat ./good.js
var a = 'foo';
$ ./out/Release/node -c ./good.js
$ echo $?
0
```

```
$ cat ./bad.js
var a foo;
$ ./out/Release/node -c ./bad.js
/Users/dave/dev/node/bad.js:1
var a foo;
      ^^^
SyntaxError: Unexpected identifier
    at startup (node.js:104:54)
    at node.js:826:3
$ echo $?
1
```

### CODE REVIEW

**Comment by OrangeDog** [comment]
Someone will want some tests submitted.

**Comment by bahamas10** [comment]
@OrangeDog tests added... example output below:

```
dave - manilla darwin ~/dev/node/test/simple (git:dave-1426873415) $ ../../out/Release/node test-cli-syntax.js 
calling /Users/dave/dev/node/out/Release/node -c /Users/dave/dev/node/test/fixtures/syntax/good_syntax.js
ok
calling /Users/dave/dev/node/out/Release/node --check /Users/dave/dev/node/test/fixtures/syntax/good_syntax.js
ok
calling /Users/dave/dev/node/out/Release/node -c /Users/dave/dev/node/test/fixtures/syntax/good_syntax_shebang.js
ok
calling /Users/dave/dev/node/out/Release/node --check /Users/dave/dev/node/test/fixtures/syntax/good_syntax_shebang.js
ok
calling /Users/dave/dev/node/out/Release/node -c /Users/dave/dev/node/test/fixtures/syntax/bad_syntax.js
ok
calling /Users/dave/dev/node/out/Release/node --check /Users/dave/dev/node/test/fixtures/syntax/bad_syntax.js
ok
calling /Users/dave/dev/node/out/Release/node -c /Users/dave/dev/node/test/fixtures/syntax/bad_syntax_shebang.js
ok
calling /Users/dave/dev/node/out/Release/node --check /Users/dave/dev/node/test/fixtures/syntax/bad_syntax_shebang.js
ok
```

**Comment by jasnell** [comment]
@bahamas10 .. thank you for this. At this point, because we are working on migrating active development to http://github.com/nodejs/node, this is not something that we would land here. The best thing would be to close this PR and open a new updated one against master on http://github.com/nodejs/node where it would have the best chance of getting a full review.

**Comment by bahamas10** [comment]
thanks @jasnell created https://github.com/nodejs/node/pull/2411

**Pull request closed without merging**
