### PR TITLE
configure: remove unused variable 'byteorder'

### PR DESCRIPTION
**Pull request by blueyed**
A separate PR, according to https://github.com/joyent/node/pull/25282#issuecomment-101307222.

### CODE REVIEW

**Comment by jasnell** [comment]
@srl295 ... I'm going to assume the `byteorder` variable was/is intended for use with the Intl stuff. Can you confirm if it's safe to remove here?

**Comment by jasnell** [comment]
@srl295 ... ping

**Comment by srl295** [comment]
Sorry. Yes, LGTM.  `sys.byteorder` is used directly on another line.

**Comment by jasnell** [comment]
Since we're not doing anything with master now, closing this here. A new PR can be opened against nodejs/node master if it's still an issue.

**Comment by blueyed** [comment]
Ok.
Sorry for the wasted time everybody, given such a minor issue (unused var).
I would have expected it to be handled better, especially after going the extra mile for a separate PR (asked for in May in https://github.com/joyent/node/pull/25282#issuecomment-101307222).

(I won't create a new PR again)

**Comment by srl295** [comment]
@blueyed not at all. thanks for catching it.

**Comment by jasnell** [comment]
@srl295 ... I see that byteorder is in configure in nodejs/node still. I
assume it's still unused there? Can it be removed?

**Comment by srl295** [comment]
@jasnell yes, still unused.

**Pull request closed without merging**
