### PR TITLE
Dual stack for node.js

### PR DESCRIPTION
**Pull request by indutny**
Should be pulled only after joyent/libuv#749.

/cc @isaacs @bnoordhuis @piscisaureus.

### CODE REVIEW

**Comment by jasnell** [comment]
@indutny ... any updates on this one?

**Comment by indutny** [comment]
@jasnell not much, I'm still not sure if the happy eyeballs should be implemented in core, instead of the user-land module.

**Comment by jasnell** [comment]
@indutny ... ok, well, given that active development has shifted over to nodejs/node, this is not likely to land here. Do you mind if we close this and if you want to pursue it then a new PR over there would make the most sense.

**Comment by indutny** [comment]
@jasnell sure! I'd say it would be enough to just open an issue and cc me in nodejs/node.

**Comment by BadgerBadgerBadgerBadger** [comment]
Where has this conversion been moved to? A link would help in keeping up with the status.

**Pull request closed without merging**
