### PR TITLE
cluster: don't assert if worker has no handles

### PR DESCRIPTION
**Pull request by sam-github**
As it says.

### CODE REVIEW

**Comment by misterdjules** [comment]
@sam-github Did you have a chance to look at [my comment](https://github.com/joyent/node/pull/8642/files#r21695691)? Otherwise LGTM. Depending on where we are with the merge from v0.10 to v0.12, we'll land it before or after the merge is done. I'll keep you posted.

Thanks!

**Comment by misterdjules** [comment]
Adding it to the 0.11.15 milestone because it's been reviewed and tested, so it should be quick and easy to land.

**Comment by sam-github** [comment]
Didn't see your comment, I'll drop the else.

**Comment by piscisaureus** [comment]
lgtm, landed in io.js: https://github.com/iojs/io.js/compare/a80b9777f262...092c224e0899
Thanks Sam!

**Comment by misterdjules** [comment]
@sam-github Thanks, landed in f260ef8c3edb45113776d1b570fe6245d4c7995e and 85360f06db82c17113fc44207e7156ac8d1c99e0 (I switched the order of the commits as 85360f06db82c17113fc44207e7156ac8d1c99e0 depends on f260ef8c3edb45113776d1b570fe6245d4c7995e). I also slightly reworded the commit message for 85360f06db82c17113fc44207e7156ac8d1c99e0, which in my opinion now better reflects what the change does.

Thank you very much again!

**Pull request closed without merging**
