### PR TITLE
deps: upgrade to npm 2.13.4

### PR DESCRIPTION
**Pull request by zkat**
These releases are included in this PR:
- https://github.com/npm/npm/releases/tag/v2.12.0
- https://github.com/npm/npm/releases/tag/v2.12.1
- https://github.com/npm/npm/releases/tag/v2.13.0
- https://github.com/npm/npm/releases/tag/v2.13.1
- https://github.com/npm/npm/releases/tag/v2.13.2
- https://github.com/npm/npm/releases/tag/v2.13.3
- https://github.com/npm/npm/releases/tag/v2.13.4

The latest version just includes a thing to make npm version work in git submodules. Previous releases are mostly just bugfixes, docs, etc.

**r**: @jasnell 

( is this enough of a CC? This is what I understood from when we talked earlier today :) )

### CODE REVIEW

**Comment by jasnell** [comment]
Yes, this is great! I'll work on getting this landed on Monday.

**Comment by jasnell** [comment]
@misterdjules @orangemocha @mhdawson ... do any of you see a reason to hold off on this? If not, I'll try to get it landed today

**Comment by jasnell** [comment]
@zkat ... just a thought... it would be good to start figuring out some kind of test suite for npm updates like this. Based on the conversation at the summit, the "contract" between node and npm is somewhat murky right now and a test suite within node may be the thing to help clear things up.

**Comment by trevnorris** [comment]
All changes are in `deps/npm/` so not sure exactly what's supposed to be reviewed, but the update LGTM.

**Comment by misterdjules** [comment]
@jasnell Before landing npm upgrades in v0.12, we need to run the npm tests against the current tip of v0.12. I do that by building node, installing it so that it's in the path, and running `make test-npm`. You will also need to install couchdb, otherwise some (significant) tests are skipped.

I run these tests on OSX, and having all tests pass on OSX is enough for me to consider a npm upgrade good to merge.

**Comment by jasnell** [comment]
Ok. Will work on that today. (@zkat sorry it keeps slipping)

**Comment by jasnell** [comment]
Landed in f693565

**Pull request closed without merging**
