### PR TITLE
doc:fix default value of `decodeURIComponent`

### PR DESCRIPTION
**Pull request by h7lin**

### CODE REVIEW

**Comment by misterdjules** [comment]
Thank you! LGTM, I would land that on v0.12 though, since it's also a problem in the v0.12 branch.

**Comment by misterdjules** [comment]
I would also add more details to the documentation for `querystring.unescape`. I'm not sure if it should mention that it uses `decodeURIComponent` and falls back to `QueryString.unescapeBuffer`, as these seem to be implementation details.

**Comment by misterdjules** [comment]
Regarding my previous comment, I think mentioning that `querystring.unescape` uses `decodeURIComponent` and falls back to a safer equivalent that doesn't throw on malformed URLs is fine.

**Comment by robertkowalski** [comment]
i added the changes in https://github.com/joyent/node/pull/9259 - the both commits should not conflict and should get merged together

**Comment by misterdjules** [comment]
@h7lin @robertkowalski Thank you both!

@h7lin Do you want to use your real name as the author name for your commit, or do you want to keep "h7lin"?

**Comment by misterdjules** [comment]
@h7lin Thank you! Landed in f1bf88395926d84fb75cc055849624caad8f0144.

**Pull request closed without merging**
