### PR TITLE
win,msi: broadcast WM_SETTINGCHANGE after install

### PR DESCRIPTION
**Pull request by orangemocha**
Fix for https://github.com/joyent/node/issues/4356

The second commit is pulled verbatim from https://github.com/iojs/io.js/commit/668bde8ac0d16382cbc98c904d8b5f55fd9fd9f0

The first commit is the delta from io.js, required to make the other commit merge cleanly.

Opening PR against v0.10 first.

### CODE REVIEW

**Comment by orangemocha** [comment]
cc @joyent/node-coreteam

**Comment by misterdjules** [comment]
LGTM, @orangemocha did you have some time to test and verify that it fixes the problem?

**Comment by orangemocha** [comment]
We tested it and verified that it sends WM_SETTINGCHANGE after this change. However, we were not able to reproduce the original issue, much like @piscisaureus mentioned in https://github.com/iojs/io.js/issues/603. But a few people have reported the issue, so we have to trust that it can happen on some systems.

**Comment by misterdjules** [comment]
@orangemocha OK, sounds good.

Regarding the commit message for [the backported commit](https://github.com/janeasystems/node/commit/0bb8136875d6d67f36d091128ec5d2e7a184416e), maybe we should format it like:
```
Backport [sha1] from io.js.

original commit message:
  The full commit mesage.
```
So that it doesn't become very confusing when the CI adds the PR-URL, the reviewer and other metadata from joyent/node.

Also, this PR is targeted to the v0.10 branch but is in the 0.12.3 milestone, so I suggest moving it to the 0.10.39 milestone.

**Comment by orangemocha** [comment]
Thanks @misterdjules! I updated both commits' messages and changed the milestone to 0.10.39.

**Comment by orangemocha** [comment]
Landed in https://github.com/joyent/node/commit/ad9947e3fa19f5f48a7872461ad79763b6ee5a51 and https://github.com/joyent/node/commit/e7c84f82c730bddb7450dc56065aab11b93ffd30.

**Comment by orangemocha** [comment]
@misterdjules will you be merging v0.10 into v0.12 before this week's release? If not I can do it. Thanks!

**Comment by misterdjules** [comment]
@orangemocha I'd like to determine first what we're doing with the RC4 deprecation fixes (see https://github.com/joyent/node/pull/14572 for example) before merging v0.10 in v0.12. If these fixes are not ready, then we might revert them in the v0.10 and v0.12 branches, and _only then_ merge v0.10 into v0.12.

Also, did you use [git-apply-pr](https://www.npmjs.com/package/git-apply-pr) to land these commits? If not, that's the recommended way to do it in v0.10, it makes the metadata format consistent for all changes. I think it's probably not documented in our contributing guidelines though, we should probably fix that.

**Comment by orangemocha** [comment]
@misterdjules Ok. 

I landed these commits manually. We could also just mark the failing unit tests as flaky and use node-accept-pull-request on v0,10 as well

**Comment by misterdjules** [comment]
@orangemocha Yes, that would probably be a good idea. We would also want to file an issue for each of the flakey tests so that we can track and fix them.

**Comment by misterdjules** [comment]
We can't really merge v0.10 and v0.12 now because of the recent changes in default ciphers list that still need some work before they are ready to ship, and I'd like to release v0.12.3 asap.

We could cherry pick the changes on v0.12, but that's a bit last minute and it's not a very severe issue. 

So I made the decision to wait for v0.10.39 to be ready to merge this into v0.12, in the meantime I'm reopening the PR so that we can track that this needs to be integrated for node v0.12.4.

/cc @joyent/node-coreteam

**Comment by orangemocha** [comment]
That sounds reasonable to me, especially considered that it's a P-3 issue. Thanks @misterdjules !

**Comment by misterdjules** [comment]
Done, [merged in v0.12](https://github.com/joyent/node/commit/f50c37d99316f2f7dc1618ea2eef4a0201a5ae0e) and shipped with node v0.12.5. Thank you!

**Comment by orangemocha** [comment]
Great, thanks @misterdjules :+1:

**Pull request closed without merging**
