### PR TITLE
dgram: make .send cb act as an "error" event handler.

### PR DESCRIPTION
**Pull request by chrisdickinson**
This allows users to provide a callback that handles potential
errors resulting from a `socket.send` call. The original behavior
of emitting the error event on the socket is preserved.

Fixes joyent/node#4846.

### CODE REVIEW

**Comment by mcollina** [comment]
Putting some more though on this one, I still think that if there is a callback, then the error should not be emitted, as they will have to 'trap' that error and ignore it, causing the exact same issue described above.
A safe way to keep backward compatibility might be to check the `callback.length`, as if it has an argument then we can assume the application is going to handle the error. What do you think?

**Comment by sam-github** [comment]
I think we should break compatibility in node v3.x, or else have a different send that does the right thing.

**Comment by mcollina** [comment]
I agree with @sam-github. Do you think it might make sense to send a PR to io.js, or I should wait after the merge happens?

**Comment by sam-github** [comment]
I don't think its worth waiting, and the io.js repo is going to move, to my knowledge, to the new org.

**Comment by cjihrig** [comment]
Closing this. The fix can be back ported from https://github.com/nodejs/io.js/commit/77266d7fadd8dfefb107ccb1e3fe97f9620f1288 and https://github.com/nodejs/io.js/commit/90daf870a00305dcb4b7bf474d8eafaed0117242.

**Pull request closed without merging**
