### PR TITLE
doc: Added link to workflow

### PR DESCRIPTION
**Pull request by paulomcnally**
On docs-nav added link to workflow

### CODE REVIEW

**Comment by robertkowalski** [comment]
lgtm

**Comment by misterdjules** [comment]
LGTM, landing with the node-accept-commit job here: http://jenkins.nodejs.org/job/node-accept-commit/64/. Commit message was slightly reworded.

Target branch for merge is v0.10, as it applies to the v0.10 documentation too. The change will bubble up to v0.12 and master when v0.10 gets merged into v0.12 and v0.12 gets merged in master eventually.

**Comment by misterdjules** [comment]
Thank you @paulomcnally :+1:

**Comment by misterdjules** [comment]
Landed in de904033fa95f0993bd8583108ac0efcda8947af, thank you again!

**Pull request closed without merging**
