### PR TITLE
Update http.markdown

### PR DESCRIPTION
**Pull request by liveinjs**
response.finished

### CODE REVIEW

**Comment by jasnell** [comment]
Hmm... unfortunately it doesn't look like this one was ever reviewed. @liveinjs , thank you for submitting this, sorry it's taken so long for someone to look at it. There are a couple of grammatical issues that should be addressed before it's landed tho; and we should verify that the `finished` property is meant to be part of the API. @cjihrig @trevnorris ... does this look fine to you?

**Comment by cjihrig** [comment]
I'm not 100% sure. Given that it's not underscored, it seems like it should be documented. If we want to document it, this needs a bit of cleanup.

**Comment by trevnorris** [comment]
Agree w/ @cjihrig

**Comment by jasnell** [comment]
New cleaned up PR opened. Closing this here.

**Pull request closed without merging**
