### PR TITLE
build: i18n: add download-icu option to vcbuild.bat

### PR DESCRIPTION
**Pull request by srl295**
For consistency with UNIX.

Fixes joyent/node#8914

### CODE REVIEW

**Comment by trevnorris** [comment]
LGTM

**Comment by srl295** [comment]
@misterdjules how does this look?

**Comment by misterdjules** [comment]
LGTM, thank you @srl295, and sorry for the delay :(

**Comment by srl295** [comment]
@misterdjules no problem! Should I rebase it against master?

**Comment by misterdjules** [comment]
@srl295 Why would you like to rebase it on master? Is there any problem with rebasing it on top of v0.12 and landing it there?

**Comment by jasnell** [comment]
@srl295 ... any reason to keep this open?

**Comment by srl295** [comment]
Would be good to get it landed but doesn't have to be against .12. Can
close here.

**Comment by jasnell** [comment]
Can you open it against master on nodejs/node?

**Pull request closed without merging**
