### PR TITLE
deps: log V8 version in profiler log file

### PR DESCRIPTION
**Pull request by bnoordhuis**
Patch from issue 800293002 authored by ben@strongloop.com

TBR=yangguo@chromium.org

Review URL: https://codereview.chromium.org/806143002

R=@trevnorris

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I can take care of forward-porting it to v0.11.

**Comment by trevnorris** [comment]
LGTM

@misterdjules @chrisdickinson Have any issues w/ this?

**Comment by bnoordhuis** [comment]
Ping.  I'd interpret the lack of replies as an implicit 'yes'.

**Comment by misterdjules** [comment]
@bnoordhuis Sorry for lagging behind :( The lack of reply on my end is more related to being busy with a lot of other stuff. I'll try to take a closer look at it today. Thanks!

**Comment by misterdjules** [comment]
@bnoordhuis The functionality definitely seem useful.

However, Node.js doesn't upgrade V8 that often, and it's frozen in v0.10 so I'm not sure I fully understand the use case for having that landed in v0.10. Is it so that when dealing with a lot of v8 logs from different Node.js/io.js versions, including node v0.10.x, it's easier to determine which profile log is from which V8/Node.js/io.js version?

Also, why isn't the test from the original upstream change back ported too?

The version is not outputted by the tick processor, is it because it's not needed or that might come later?

Thank you!

**Comment by misterdjules** [comment]
@bnoordhuis Also, this is unrelated to the change itself, but I always have a hard time running V8's profiler on OS X and Linux. On OS X, `d8` doesn't seem to build out of the box. On Linux, I always have to patch the generated makefiles and invoking `linux-tick-processor` directly segfaults, so I have to to use `cat v8.log | deps/v8/out/native/d8 ./deps/v8/tools/splaytree.js  ./deps/v8/tools/codemap.js ./deps/v8/tools/csvparser.js ./deps/v8/tools/consarray.js ./deps/v8/tools/profile.js ./deps/v8/tools/profile_view.js ./deps/v8/tools/logreader.js ./deps/v8/tools/tickprocessor.js ./deps/v8/tools/tickprocessor-driver.js`.

Am I missing something, or is it just the current state of the tools around profiling in v0.10?

**Comment by bnoordhuis** [comment]
> Is it so that when dealing with a lot of v8 logs from different Node.js/io.js versions, including node v0.10.x, it's easier to determine which profile log is from which V8/Node.js/io.js version?

Yes, exactly.  If a tool doesn't know the version, it can't select the proper tick processor.  The format changes quite often.

> Also, why isn't the test from the original upstream change back ported too?

I couldn't get the V8 C++ test suite in v0.10 to build, last time I tried it.

> is it just the current state of the tools around profiling in v0.10?

In a word: yes.

**Comment by tjfontaine** [comment]
Since this is in upstream I'm fine with the change, LGTM

**Comment by misterdjules** [comment]
@bnoordhuis Thank you for your response, the change LGTM.

**Comment by trevnorris** [comment]
Thanks. Landed in 431eb172f97.

**Comment by misterdjules** [comment]
Also, just for your information, @jasnell plans to work on [making V8's tests suite run with `make test`](https://github.com/joyent/node/issues/9102) soon.

**Comment by misterdjules** [comment]
@trevnorris Do you want to take care of merging this in v0.12 soon, or should I create an issue to track that?

**Comment by trevnorris** [comment]
@misterdjules Go ahead and create an issue and assign it to me.

**Pull request closed without merging**
