### PR TITLE
v8: fix let bindings in for loops

### LINKED ISSUE #9113: Bug: for loop becomes endless loop in 0.11.15
The following one-liner runs in an endless loop on 0.11.15.
node --harmony --use-strict -e 'for (let i = 0; i < 3; ++i) { if (i == 1) { continue; } }'

Replace 'let' with 'var' to avoid the bug.

Bug does not show up in 0.11.14.

Tested with a clean docker image, created like this:
FROM node:0.11.15
CMD node --harmony --use-strict -e 'for (let i = 0; i < 3; ++i) { if (i == 1) { continue; } }'

### PR DESCRIPTION
**Pull request by misterdjules**
This PR:
- Adds [the floating patch that fixes let bindings and continue statements in for loops](https://github.com/joyent/node/commit/072460265226c047369558b23e9ff2748965bf6c).
- Adds [a test](https://github.com/joyent/node/commit/00ca880a7013d75820bdf087698930d6fc11cb92) that makes sure that this patch is floated in future V8 upgrades if needed.

They are in two separate commits so that every time we float the patch, we don't float the test too.

This PR is based off [another PR that downgrades V8 to the actual proper stable version for node v0.12](https://github.com/joyent/node/pull/18206), which is the reason why there are more commits than the two highlighted above.

Once #18206 lands, this PR will be rebased on top of v0.12 and will only include these two commits.

Fixes #9113 and #14411.

/cc @joyent/node-coreteam  and especially @mhdawson.

### CODE REVIEW

**Comment by cjihrig** [comment]
The test LGTM. The floating patch appears to be correct.

**Comment by misterdjules** [comment]
Thank you @cjihrig!

**Comment by misterdjules** [comment]
Rebased on top of v0.12, landing soon.

**Comment by misterdjules** [comment]
Landed in 2a5f4bd7ce40b9537c5d77558687858c7246d896 and cb55a05f528f57e350063f618274b5a182261387.

**Pull request closed without merging**
