### PR TITLE
V8 lateral 3.28 update

### PR DESCRIPTION
**Pull request by misterdjules**
This continues the work done in https://github.com/joyent/node/pull/9185. It's basically the same PR with some added floating patches and the hidden files put back in.

Tested on [UNIX](http://jenkins.nodejs.org/job/node-review-unix-julien/53/) and [Windows](http://jenkins.nodejs.org/job/node-review-windows-julien/45/). The one test failing on Windows might be a flakey test, we'll need to make sure of that before landing this PR.

Fixes https://github.com/joyent/node/issues/9241.

### CODE REVIEW

**Comment by trevnorris** [comment]
@misterdjules Thanks much for taking the time to do this. Very appreciated.

**Comment by misterdjules** [comment]
The [test that was failing on Windows in the previous tests run](http://jenkins.nodejs.org/job/node-review-windows-julien/45/) does not fail anymore, although [another test timed out](http://jenkins.nodejs.org/job/node-review-windows-julien/47/). That test seems to be flakey too. In other words, we have more flaky tests and we'll need to take care of them, but I don't think they've been introduced by this PR.

**Comment by misterdjules** [comment]
`test/pummel/test-postmortem-*` tests also all pass. /cc @joyent/node-coreteam.

**Comment by misterdjules** [comment]
Just squashed the commit adding hidden files back into the main upgrade commit.

@trevnorris What's your opinion about landing that in the upcoming v0.12.3 release?

**Comment by trevnorris** [comment]
@misterdjules No qualms here.

**Comment by trevnorris** [comment]
LGTM

**Comment by misterdjules** [comment]
Thank you @trevnorris! Landing soon.

**Comment by misterdjules** [comment]
Landed in 32166a90cf126e4738b3ac81496ba1a46a23281d, beff91c44e7ba13035d1dbd05cf2bef7a7d65f82, ace398ed425e5b640fa4922697d317755ef8a652,  9a960c270c4ca48e05ccc915135845a1e2120e94 5b2bf92211278eba3ff1cc954cc42060b75b526f and 712cb4340b6c784779b986b0fcfe3564ee173ccf. Thank you!

**Pull request closed without merging**
