### PR TITLE
Merge 0.10 into 0.12

### PR DESCRIPTION
**Pull request by misterdjules**

### CODE REVIEW

**Comment by piscisaureus** [comment]
lol

**Comment by misterdjules** [comment]
This merge in its current state only introduces two regressions:
* test-crypto-stream.js fails on all platforms. I suggest to fix this test in a later commit.
* test-fs-access.js fails on most build agents. This test seems to fail for not being able to create a test file. I suggest fixing this test in a subsequent commit too.

You can check out the test results for [Windows](http://jenkins.nodejs.org/job/node-review-windows-julien/) and [UNICes](http://jenkins.nodejs.org/job/node-review-unix-julien/).

@tjfontaine @trevnorris Please let me know what you think.

**Comment by tjfontaine** [comment]
I would rather continue to debug the regressions post the merge, so please go ahead with this, LGTM thanks for all your hard work on it

**Comment by misterdjules** [comment]
Landed in 0c7f6ca83091eb5516d07153f35f851e47f753ee, 893fe4c67d7e769efb090264a5a19b41d130987b, 7325fe7987ee134589a9f44743ab24d69b305eb5, e64ee2b3f7b4067101b0291f1add842353cd6865, 10703774f01a4005fc74d6b4131c713259e81657, 7f4b45dbe8d9e2b53779aae225f939368842805d and 21c2636c9a7ee3473addcee0a6cd608e8952be79.

It's a bit messy, as I created a `merge-0-10-into-0-12` branch off of v0.12 first, then merged v0.10 into that branch, and then rebased `merge-0-10-into-0-12` on top of v0.12. Because one commit was introduced on v0.12 in the meantime, I had to merge v0.12 into `merge-0-10-into-0-12` again, and then pushed `merge-0-10-into-0-12` to v0.12.

Next time, I'll make sure to have a cleaner process.

**Comment by trevnorris** [comment]
Well, hopefully next time we merge more frequently so it won't be such a mess. :)

**Pull request merged**
