### PR TITLE
build,win: set env before generating projects

### PR DESCRIPTION
**Pull request by orangemocha**
vcbuild.bat calls python configure before setting GYP_MSVS_VERSION,
so SelectVisualStudioVersion (tools\gyp\pylib\gyp\MSVSVersion.py)
defaults to 'auto' and selects VS 2005.

vcbuild sets the environment in the current shell, so this issue
would manifest itself only on the first invocation of the script
in any given shell windows.

### CODE REVIEW

**Comment by orangemocha** [comment]
@joyent/node-coreteam , ok to include this fix in 0.12.3?

**Comment by jasnell** [comment]
LGTM

**Comment by misterdjules** [comment]
@orangemocha LGTM at first sight, testing right now.

**Comment by misterdjules** [comment]
Worked fine on my Windows 7 development setup. Thank you @orangemocha!

**Comment by misterdjules** [comment]
@orangemocha Feel free to land it using the node-accept-pull-request Jenkins job.

**Comment by orangemocha** [comment]
Thanks guys! Landed in https://github.com/joyent/node/commit/a58b17456a7fa4ff846c4883b96d6dee7e46a62f

**Pull request closed without merging**
