### PR TITLE
deps: upgrade npm to 2.7.1

### PR DESCRIPTION
**Pull request by othiym23**
`npm@2.7.1` is a pretty hefty release. I've included the four most significant changes below, and there are many others in the full `CHANGELOG.md`.
- [`6823807`](https://github.com/npm/npm/commit/6823807bba6c00228a724e1205ae90d67df0adad)
  [#7121](https://github.com/npm/npm/issues/7121) `npm install --save` for Git
  dependencies saves the URL passed in, instead of the temporary directory used
  to clone the remote repo. Fixes using Git dependencies when shrinkwwapping.
  In the process, rewrote the Git dependency caching code. Again. No more
  single-letter variable names, and a much clearer workflow.
  ([@othiym23](https://github.com/othiym23))
- [`abdd040`](https://github.com/npm/npm/commit/abdd040da90932535472f593d5433a67ee074801)
  `read-package-json@1.3.2`: Provide more helpful error messages when JSON
  parse errors are encountered by using a more forgiving JSON parser than
  JSON.parse. ([@smikes](https://github.com/smikes))
- [`c56cfcd`](https://github.com/npm/npm/commit/c56cfcd79cd8ab4ccd06d2c03d7e04030d576683)
  [#7525](https://github.com/npm/npm/issues/7525) `npm dedupe` handles scoped
  packages. ([@KidkArolis](https://github.com/KidkArolis))
- [`4ef1412`](https://github.com/npm/npm/commit/4ef1412d0061239da2b1c4460ed6db37cc9ded27)
  [#7075](https://github.com/npm/npm/issues/7075) If you try to tag a release
  as a valid semver range, `npm publish` and `npm tag` will error early instead
  of proceeding. ([@smikes](https://github.com/smikes))

### CODE REVIEW

**Comment by misterdjules** [comment]
@othiym23 Moving to the 0.12.2 milestone because the current plan is to have v0.12.1 be v0.12.0 + the OpenSSL upgrade. Node v0.12.1 would thus ship with npm 2.5.1. I know it's different than our initial idea and what we talked about in #libuv. Do you have any objections to that?

**Comment by othiym23** [comment]
If it gets a patched 0.12.1 out faster, I have no objections, although I think the risk of including the upgraded npm is very low.

**Comment by misterdjules** [comment]
Thank you for your input @othiym23!

**Comment by misterdjules** [comment]
Closing in favor of #9443.

**Pull request closed without merging**
