### PR TITLE
Fix armv6 detection

### PR DESCRIPTION
**Pull request by misterdjules**
This PR ports https://github.com/iojs/io.js/pull/559 to joyent/node.

### CODE REVIEW

**Comment by misterdjules** [comment]
@joyent/node-coreteam Adding to the 0.12.2 milestone with P-2 because it would probably help a lot of Raspberry-PI users. These changes [have been confirmed to work by a Raspberry-Pi user](https://github.com/joyent/node/pull/9068#issuecomment-77487227).

**Comment by misterdjules** [comment]
I believe this would fix https://github.com/joyent/node/issues/14186, https://github.com/joyent/node/issues/7222, https://github.com/joyent/node/issues/9163, https://github.com/joyent/node/issues/8589, https://github.com/joyent/node/issues/8549 and https://github.com/joyent/node/issues/4540.

**Comment by magic890** [comment]
Here is the official patch from V8 team: https://github.com/v8/v8-git-mirror/blob/master/src/base/cpu.cc#L483-L499

I have created a pull request to solve this issue: #25625

**Comment by Fishrock123** [comment]
Since armv6 works in Node > 1, I am going to assume this is no longer necessary.

**Pull request closed without merging**
