### PR TITLE
tls: revert disable RC4 and cipher lists changes

### PR DESCRIPTION
**Pull request by misterdjules**
This reverts commit 67d9a56251c4491beacb666ba5833574d0cf0d12.

This commit actually reverts both
67d9a56251c4491beacb666ba5833574d0cf0d12 and
02a549ed2b2afe85d8ff0335b6684ad54023afb7 (both related to ciphers list
changes). It does it in one commit because reverting
02a549ed2b2afe85d8ff0335b6684ad54023afb7 results in an empty commit.

These changes are not yet ready to be released, and before they are we
want to be able to publish new releases. We're reverting them so that we
can submit a new PR that will contain all these changes plus what's
necessary to be able to land them properly.

Conflicts:
    src/node.cc

/cc @joyent/node-tsc

### CODE REVIEW

**Comment by misterdjules** [comment]
This had already been discussed with @jasnell and others during our weekly meeting, but I'd rather give a heads up than bypassing the PR/review process.

**Comment by mhdawson** [comment]
Are you hoping to get the change in for the release next week ?

**Comment by misterdjules** [comment]
@mhdawson I'll try to, but I don't think I'll have time for that.

**Comment by misterdjules** [comment]
@joyent/node-collaborators Can I get your feedback on this? This would block releasing v0.10.39 with the OpenSSL upgrade.

**Comment by shigeki** [comment]
I can not figure out the reason why RC4 is back after reading discussions in this PR. Is it for backward compatibility in node-v0.10.x? Or is there another reason to cause an issue with this patch that was applied?

**Comment by misterdjules** [comment]
@shigeki The reason why I want to revert these changes before doing a new v0.10.x release is that they are not quite ready yet. [Another PR](https://github.com/joyent/node/pull/14572) was submitted to fix most of the concerns we had, but it hasn't been approved and thus hasn't landed yet.

Instead of rushing to land that PR, I suggest to get a new release with the OpenSSL upgrade out of the door asap, and land it for the next release.

Please let me know if that clarifies things.

**Comment by misterdjules** [comment]
@shigeki Let me know if my answer clarifies things, I'm waiting for a review in this PR to start the release process for v0.10.39 with the OpenSSL upgrade. However, I don't want to force anyone to approve it, if you still have any concern, please feel free to raise them :)

**Comment by jasnell** [comment]
Julien, I'm back from the camping trip but not officially back from
vacation until Monday. I'll try to review in the next couple of days but
still have quite a bit of family stuff going on

**Comment by misterdjules** [comment]
@jasnell No worries, I'm not expecting you to review code when you're on vacation :) Thank you very much for the note though and enjoy your time off :+1:

**Comment by shigeki** [comment]
@misterdjules Thanks. I've got it that we need some treatments before deprecation of RC4. LGTM.

**Comment by misterdjules** [comment]
@shigeki Thank you for the review! No regression found on [Windows](http://jenkins.nodejs.org/job/node-review-windows/199/) and [UNIX](http://jenkins.nodejs.org/job/node-review-windows/199/), and `test/external/ssl-options/test.js` passes (I ran it manually). Landing asap.

**Comment by misterdjules** [comment]
Landed in dcb7ef2.

**Pull request closed without merging**
