### PR TITLE
buffer: reword Buffer.concat error message

### PR DESCRIPTION
**Pull request by chrisdickinson**
this brings the error messaging in line with other node TypeError messages.

fixes joyent/node#7766.

### CODE REVIEW

**Comment by trevnorris** [comment]
@chrisdickinson was this merged?

**Comment by misterdjules** [comment]
@trevnorris It hasn't been merged. Technically it could be considered as an API change, but it's very unlikely that anyone relies on this error's message if/when catching it.

@joyent/node-coreteam Is anyone opposed to landing it in v0.12? If not, I'll land it in v0.12 and master, otherwise just in master.

Thank you!

**Comment by trevnorris** [comment]
I'm fine landing this on v0.12.

**Comment by jasnell** [comment]
LGTM. Note, #9174 will touch this also.

**Comment by misterdjules** [comment]
This actually also affects v0.10, so we could land it there first. @joyent/node-coreteam Thoughts?

**Comment by cjihrig** [comment]
No reason it couldn't go in 0.10. Just not sure if it's worth the time to do so.

**Comment by misterdjules** [comment]
@cjihrig Considering there are far more users of v0.10.x than users of v0.12.x, I think it's worth the time to land in v0.10. Especially since it's quick to "backport" to v0.10 and then to merge in v0.12 and master.

**Comment by misterdjules** [comment]
@joyent/node-coreteam Adding to the 0.10.37 milestone and will land in v0.10 asap as it's not an API change nor a breaking behavior change.

**Comment by misterdjules** [comment]
Landed in d01a900, and merged in v0.12 and master with b0425f0 and a995a6a. Thank you @chrisdickinson!

**Comment by piscisaureus** [comment]
@chrisdickinson Are you going to PR this to iojs too?

**Comment by cjihrig** [comment]
@piscisaureus taken care of.

**Pull request closed without merging**
