### PR TITLE
doc: document dynamic tracing and postmortem debugging

### PR DESCRIPTION
**Pull request by davepacheco**
This is still a draft.  I'm not sure how we want to incorporate this into the docs.  I just included it as a new section (since there's other stuff like Modules, Add-ons, and Debugger that aren't really APIs).  However it gets integrated, I think there's high demand for canonical documentatian for this, and it should probably live with the Node repo and be part of the web site.

### CODE REVIEW

**Comment by Fishrock123** [comment]
This seems very useful. cc @chrisdickinson?

**Comment by davepacheco** [comment]
I'm also planning to better document the MDB stuff, since that also lives in the Node repo.

**Comment by geek** [comment]
LGTM

**Comment by davepacheco** [comment]
I've added a second commit for postmortem debugging documentation. CC @tjfontaine

**Comment by davepacheco** [comment]
Much of the postmortem debugging docs incorporates content from Joyent's Node dev center.

**Comment by tjfontaine** [comment]
I also have an old commit that never quite turned into a PR, https://github.com/tjfontaine/node/commit/74f395ca9486a13559c73a7cc40c75ec3a3c9817 I would love to see the ETW, SystemTap examples included into this documentation in a follow up commit, if someone would be willing to verify it. It would also be nice to include ktap examples, which shouldn't be too far off from the DTrace ones.

**Comment by geek** [comment]
@robertkowalski thoughts on us migrating this over to the website under a debugging section within /tutorials?

**Comment by robertkowalski** [comment]
@geek good idea! I am still working on the node-doc-tool so I don't have time this week but I like the idea!

**Comment by jasnell** [comment]
@davepacheco ... what would you like to do with this? Is it still a work in progress?

**Comment by davepacheco** [comment]
I would still love to see this folded into the Node documentation, particularly the Dynamic Tracing bit.  I've moved most of the postmortem debugging stuff to http://github.com/joyent/mdb_v8.  It would still be useful to reference it from the Node documentation, though maybe that's discussion for the postmortem WG.

**Comment by jasnell** [comment]
ok. getting this in would be good, just not sure exactly how. I'm in the process of getting the outstanding PRs in joyent/node cleaned up. This one may need to be refactored and moved over to either nodejs/node or nodejs/documentation. Not sure which just yet. Either way, I know this won't be landing here.

**Comment by jasnell** [comment]
@davepacheco ... thinking about it further, the best bet on this one may be to work with the nodejs/docs working group and get this documented in nodejs/node first. Then, we can cherry pick it back as necessary. Opening a new PR against master on nodejs/node would ensure that it gets plenty of attention as there aren't very many who are looking over the PRs here.

**Pull request closed without merging**
