### PR TITLE
tls: updated cipher defaults

### PR DESCRIPTION
**Pull request by jasnell**
io.js recently updated the default cipher suite.
See
https://github.com/iojs/io.js/commit/77f35861d0217273b9e478f5d35bd7d8e47
1e14f

This helps, for instance, with the "new" 13-year old
RC4 Bar Mitzvah vulnerability. This commit pulls over
the io.js commit.

### CODE REVIEW

**Comment by misterdjules** [comment]
I think it's important to keep the original author and commit message.

I've ported some changes from io.js in the past few weeks and I've started using the following form of commit messages: https://github.com/joyent/node/commit/61fe1fe21ba281b05b90a632e2dad29eefb14a0a.

What do you think?

**Comment by jasnell** [comment]
+1. Good plan. I can update the commit message for this one accordingly if
you'd like.

**Comment by misterdjules** [comment]
Yes please! Usually what I do is that I use the following command line to port a change from one repo (V8, libuv, io.js, etc.) to my local node repository:
```
git --git-dir=/path/to/local/repo/clone/.git/ format-patch -k -1 --stdout sha | git am
```
where `sha` is the commit hash of the change I want to port and `/path/to/local/repo/clone` is the path to a local clone of the repository where the change is.

Then I use `git commit --amend` (or `git rebase` and reword) to change the commit message.

**Comment by jasnell** [comment]
Replacing with another PR with the io.js pr commit message...

**Comment by piscisaureus** [comment]
@jasnell 
I hope that you're aware that you can actually *update* an existing pull request? I notice that you always open new ones, but that really isn't necessary.

Try it out: `git push <your-remote-name> +HEAD:tls-update-cipher-suite-defaults`

**Comment by jasnell** [comment]
Thanks. I do. I just tend towards a natural aversion to changing history.
It's been a personal preference but I can edit the original ones just as
easily.

**Comment by piscisaureus** [comment]
> I just tend towards a natural aversion to changing history.

For repos that other people use like joyent/node, indeed, don't force push.
But for PRs it's fine; it keeps the noise down a little bit, and it makes it easier to track how a PR evolves over time.

**Pull request closed without merging**
