### PR TITLE
Merge v0.10 to v0.12

### PR DESCRIPTION
**Pull request by trevnorris**
There were a lot of changes to crypto. @indutny has one of those fixes.

Also an issue with additional tests to child process in v0.10 that are failing in v0.12.

/cc @tjfontaine @chrisdickinson

### CODE REVIEW

**Comment by cjihrig** [comment]
@trevnorris yes, you can just squash it and close the PR. The only thing left to do on that PR is reword the commit message.

**Comment by misterdjules** [comment]
@trevnorris I'm off until January 4th, until then I won't have time to look at any PR or issue on GitHub. Did you get my latest email @nodejs.org about this merge and about my time off?

**Comment by indutny** [comment]
@trevnorris going to fix that crypto thing.

**Comment by misterdjules** [comment]
@trevnorris What's the status on this merge? What do we need to do to move this forward?

**Comment by misterdjules** [comment]
@trevnorris @tjfontaine Just FYI, I started the merge from scratch as it's not clear if we can re-use the resolve conflicts info from the previous merge. I'll keep you posted on my progress.

**Comment by trevnorris** [comment]
Being done in https://github.com/joyent/node/pull/9018.

**Pull request closed without merging**
