### PR TITLE
DTLS - Draft approach

### PR DESCRIPTION
**Pull request by migounette**
All,

This is a flush of the work done on DTLS support for node 0.11.x, this is not a stabilized version BUT I need comment how I modified the tls wrap, dgram and stream classes.

The goal was to keep the tls.cpp a maximum unchanged for the Datagram support and keep the Stream support unchanged.
# Main changes philosophy

I tried to keep the maximum common code with TLS, DTLS is very close thanks to the OpenSSL
So, I extended Stream | TLSCallback | UDP in order to have an agnostic Callback wrapper (not stream colorized)
And I add an interface to needed function (Read | Write for Stream and Send | Receive for Datagram)
# TODO

A lot stuff to be done in order to insure that is fully functional
- Pass TSL tests (insure that there is no regression)
- Add DTLS tests in /tests sections
- Check DTLS algorithm used
- ...
- node.gyp (uncomment for js inclusion)

I will work on it in order to complete the work. But first I need feedback to insure that I am on the good tracks
# How to test

[Server]
set NODE_PATH=C:\node.dtls\lib
cd c:\node.dtls\tests
..\debug\node .\dtls-test.js

[Client]
With OpenSSL
Go to .\bin\PEM
..\openssl.exe s_client -connect localhost:8000 -dtls1

Then type any text and return, the server replies pong - {your text}

### CODE REVIEW

**Comment by oceddi** [comment]
I second a comment that was made earlier.  There is a big wave of interest coming in the IoT space for DTLS running with the CoAP protocol.  Those of us wanting to experiment implementing server side solutions for these systems are keenly anticipating native DTLS support in node.

**Comment by migounette** [comment]
Well,

I can certainly re-start the implementation of DTLS, but I am a bit disappointed. I was waiting 0.12.x for starting the operation, meanwhile I have 0.11.15 and io.js.

More than one year that the prototype was ready. In fact more push from the community is the key.

I need feedback on the js interfaces... feedback welcome

**Comment by sam-github** [comment]
@migounette I think this is appropriate for targetting in node, because its the exposure of more OpenSSL features. I symphasize with your frustration about lack of comment. I suggest you'd get better traction if you

1. add API documentation, digging through a mountain of code to determine the API is discouraging
2. PR to https://github.com/iojs/io.js, it isn't feature frozen (like joyent/node 0.12)

**Comment by marcnicholas** [comment]
@migounette If you're able to provide some API docs and get this PR'd to io.js, I'll happily test and give feedback.

I'd love this for COAP and echo the sentiment that COAP is about to get big, and a node-like infrastructure needs to support DTLS to be taken seriously in this context.

Thank you for taking the time to put the prototype together and I'm sorry it's not been received better.

-m

**Comment by Rantanen** [comment]
DTLS is also part of ICE (WebRTC) so this would be needed for a pure Node/JS implementation of WebRTC.

I'm up for testing this feature if the PR was available for Node 0.12.x or io.js.

**Comment by guymguym** [comment]
:+1:

**Comment by Rantanen** [comment]
Given WebRTC needs this, I've been working on a JavaScript implementation while waiting for native Node.js support: https://github.com/Rantanen/node-dtls

From security standpoint this is a stopgap solution for a native module given I don't really trust my own code for such security critical work. (Although having gone through OpenSSL codebase while building the JS implementation, I'm not sure if I should trust that either. :stuck_out_tongue:)

Mainly I'm bringing this to the general attention from an API standpoint. Ideally I'd like to implement the proposed Node.js DTLS API.

I haven't really gone through the API proposed in this pull request, but I've had a brief look at it and there seem to be some fundamental differences. Biggest one that I could see was `DTLSSocket` inheriting `dgram.Socket`:

`dgram.Socket`s are unbound sockets that are able to send packets to any recipient, ie. the `send()` method requires explicit recipient port and address. However `DTLSSocket` is strictly tied (through the handshake) to a specific remote endpoint.

##### Proposition

My current API mimics the `tls.createServer` calls to create a `DtlsServer` instance, which uses similar `secureConnection` events to expose the actual secure `DtlsSocket`s. However unlike `tls.Socket` the `DtlsSocket` does not implement the Stream interface but instead the `send()` method similar to `dgram.Socket.send()` but without the remote port/address parameters.

My project doesn't implement client handshakes yet, but the planned API would again follow the `tls` API by providing a method similar to `tls.connect()`, which would yield a `DtlsSocket` object that adapts the `dgram.Socket` interface.

##### Recap

- Mimic the `createServer` and `connect` methods from Node's `tls` module.
- Adapt the actual Socket read/write interface from `dgram.Socket` but tie it to a specific endpoint instead of providing parameters to define remote port/address per function call.

**Comment by rgillan** [comment]
Hi, I know this has been floating around for a long time but is there an update/plan for inclusion of DTLS natively in node.js?  As many others have stated, it's a mandatory requirement for almost any IoT/smart X project and it's applications that node.js will shine at.

**Comment by benjsicam** [comment]
Agree. Native DTLS support for Node.js is needed.

**Comment by jasnell** [comment]
While this is definitely something that is important, given that the active development branch has shifted to http://github.com/nodejs/node, it's likely best to close this here, update it, and get it opened against the other repo. @joyent/node-tsc , any objections to closing this here?

**Comment by rgillan** [comment]
absolutely in favour

**Comment by jasnell** [comment]
@rgillan ... just to be clear, is that in favor or closing here and reopening against nodejs/node master?

**Comment by rgillan** [comment]
I am in favour of it being reopened against nodejs/node master, although know others are working on it as well.

**Comment by jasnell** [comment]
Ok, Opened a new issue in nodejs/node to track and continue the discussion. Closing this PR here as it will never land here. Please do continue the discussion there! Thanks all!

**Comment by alexrepin** [comment]
bad discussion!

**Pull request closed without merging**
