### PR TITLE
Don't share dgram sockets that are implicitly bound

### PR DESCRIPTION
**Pull request by sam-github**
Server sockets should be shared by default, and client sockets should be
exclusive by default. For net/TCP, this is how it is, for dgram/UDP, its
a little less clear what a client socket is, but a socket that is
auto-bound during a dgram.send() is not usefully shared among cluster
workers, any more than an outgoing TCP connection would be usefully
shared.

See https://github.com/joyent/node/pull/8027#issuecomment-60817257

/to @asilvas @bnoordhuis  @rmg

Test triggers a pre-existing bug, so is based on https://github.com/joyent/node/pull/8642.

### CODE REVIEW

**Comment by sam-github** [comment]
@misterdjules Happy New Year! Do you have time to take a look at this?

**Comment by misterdjules** [comment]
@sam-github Thanks, happy new year to you too :) I'm taking a look at #8642 first, and then I'll take a look at this one. #8642 looks good so far, and depending on where we are with the merge of v0.10 to v0.12, it'll land before or after it.

How does that sound?

**Comment by misterdjules** [comment]
@sam-github LGTM. This will land after #8642, so we'll need to rebase this branch at some point.

Not landing until we know we're we stand regarding the ongoing merge of v0.10 into v0.12.

Thanks!

**Comment by misterdjules** [comment]
Adding it to the 0.11.15 milestone because it's been reviewed and tested, so it should be quick and easy to land.

**Comment by sam-github** [comment]
I'm happy to rebase, ping me when you want it.

**Comment by piscisaureus** [comment]
lgtm, landed in io.js: https://github.com/iojs/io.js/commit/a32b92dbcfc8a3a8b2409bb2ace2233ebe327888
Another thanks :p

**Comment by piscisaureus** [comment]
The patch was reverted in io.js; https://github.com/iojs/io.js/pull/279

**Comment by piscisaureus** [comment]
@sam-github 

The patch was reverted because it makes test-cluster-dgram-2 fail. This test hangs because `cluster.disconnect()` in the master doesn't close the non-shared UDP sockets in the client so they keep the process open.

**Comment by misterdjules** [comment]
@piscisaureus Thanks for the heads-up!

**Comment by sam-github** [comment]
Fixed in 0b827a0

**Comment by sam-github** [comment]
cf. https://github.com/iojs/io.js/pull/325

**Comment by misterdjules** [comment]
@tjfontaine @trevnorris @cjihrig @orangemocha OK to land https://github.com/iojs/io.js/pull/325 (the fixed version of this PR) in master?

**Comment by cjihrig** [comment]
+1 from me

**Comment by trevnorris** [comment]
@misterdjules +1

**Comment by misterdjules** [comment]
@cjihrig @trevnorris Thanks! Will land it asap.

**Comment by misterdjules** [comment]
Landed in e42c4a3. Thanks again @sam-github!

**Pull request closed without merging**
