### PR TITLE
tls: more secure defaults

### PR DESCRIPTION
**Pull request by jasnell**
Port of io.js commit: https://github.com/iojs/io.js/commit/77f35861d0217273b9e478f5d35bd7d8e47

Original commit message:

This updates the default cipher suite to an more secure list, which
prefers strong ciphers with Forward Secrecy. Additionally, it enables
`honorCipherOrder` by default.

Noteable effect of this change is that the insecure RC4 ciphers are
disabled and that Chrome negotiates a more secure ECDHE cipher.

Reviewed-By: Ben Noordhuis info@bnoordhuis.nl
Reviewed-By: Fedor Indutny fedor@indutny.com
PR-URL: https://github.com/iojs/io.js/pull/826

### CODE REVIEW

**Comment by jasnell** [comment]
Replaces https://github.com/joyent/node/pull/14192 with updated commit message

**Comment by misterdjules** [comment]
Is it still relevant after #14383 has been created?

**Comment by jasnell** [comment]
By itself, no. Just taking the updated defaults is not quite enough. The
updated PR incorporates this change plus the additional command line
switches.

**Comment by misterdjules** [comment]
OK :+1: Should we close this one then?

**Comment by jasnell** [comment]
Yes. I'll do that shortly.

**Pull request closed without merging**
