### PR TITLE
deps upgrade npm to 2.5.1

### PR DESCRIPTION
**Pull request by othiym23**
From the release notes:

This release doesn't look like much, but considerable effort went into ensuring that npm's tests will pass on io.js 1.1.0 and Node 0.11.16 / 0.12.0 on both OS X and Linux.

**NOTE:** there are no actual changes to npm's code in `npm@2.5.1`. Only test code (and the upgrade of `request` to the latest version) has changed.
#### `npm-registry-mock@1.0.0`:
- [`0e8d473`](https://github.com/npm/npm/commit/0e8d4736a1cbdda41ae8eba8a02c7ff7ce80c2ff) [#7281](https://github.com/npm/npm/issues/7281) `npm-registry-mock@1.0.0`: Clean up API, set `connection: close`.
  ([@robertkowalski](https://github.com/robertkowalski))
- [`4707bba`](https://github.com/npm/npm/commit/4707bba7d44dfab85cc45c2ecafa9c1601ba2e9a)
  Further update tests to work with `npm-registry-mock@1.0.0`.
  ([@othiym23](https://github.com/othiym23))
- [`41a0f89`](https://github.com/npm/npm/commit/41a0f8959d4e02af9661588afa7d2b4543cc21b6)
  Got rid of completely gratuitous global config manipulation in tests.
  ([@othiym23](https://github.com/othiym23))
#### MINOR DEPENDENCY TWEAK
- [`a4c7af9`](https://github.com/npm/npm/commit/a4c7af9c692f250c0fd017397ed9514fc263b752)
  `request@2.53.0`: Tweaks to tunneling proxy behavior.
  ([@nylen](https://github.com/nylen))

Also includes a patch to node's `Makefile` that more tightly constrains the `$PATH` available to npm when running `make test-npm`.

### CODE REVIEW

**Comment by DomT4** [comment]
@othiym23 Does this remove the need to patch ` npm ` for ` iojs `?

**Comment by othiym23** [comment]
@DomT4 this is unrelated to that issue, which requires that TooTallNate/node-gyp#564, or something like it, be merged and a new version of `node-gyp` be published.

**Comment by DomT4** [comment]
Ah I see, Thanks Forrest.

**Comment by tjfontaine** [comment]
@misterdjules had already been working to verify the tests this morning, thanks @othiym23 for submitting this PR

LGTM

**Comment by misterdjules** [comment]
The upgrade to npm 2.5.1 LGTM, thank you again @othiym23 for your help!

However I'd like to leave out the change to the Makefile for now because I'd rather take the time to review it carefully, which I can't do properly now.

I had submitted [a similar PR that makes `test-npm` use the node binary built from the local checkout](https://github.com/joyent/node/pull/9107). One of the differences with your commit is that it preserves `$PATH`, I'm not sure if it's better, but let's discuss that over there if you don't mind.

**Comment by misterdjules** [comment]
Landed in 087a7519cea9b8aed23f4c03111da724cf20a94f, thank you!

**Pull request closed without merging**
