### PR TITLE
deps: upgrade npm to 2.5.0

### PR DESCRIPTION
**Pull request by misterdjules**

### CODE REVIEW

**Comment by misterdjules** [comment]
@othiym23 Ran make `test-npm` on OS X and, besides [the keepAlive/mock-registry issue we already talked about during the latest npm upgrade](https://github.com/joyent/node/pull/9086#issuecomment-71764613), the tests suite failed with the following errors: https://gist.github.com/misterdjules/c8b6d5117a22cbff29c6 and https://gist.github.com/misterdjules/53872c9d9f6d3ca76725.

I'm currently building binary packages and installers and will run basic smoke tests like installing packages from the public registry on as many supported platforms as possible.

**Comment by misterdjules** [comment]
@othiym23 I've built binary releases for all supported platforms, and so far the smoke tests I ran all pass.

So here's what I would like to do before landing this:
1) Have you review this PR if you have some time, just to make sure I haven't missed anything obvious.
2) Run `make test-npm` after installing a `npm-registry-mock` with a fix for the keepAlive issue. Please let me know when you publish a version with a fix somewhere.

How does that sounds?

**Comment by othiym23** [comment]
That sounds great, and I will get to this before I cut tomorrow's release, at the latest.

**Comment by misterdjules** [comment]
Some tests are still failing when ran with a node binary built from the v0.12 branch. npm just released 2.5.1 with all tests passing, so closing this PR in favor of another PR that upgrades npm to 2.5.1.

**Pull request closed without merging**
