### PR TITLE
test:lint Lint added for test folder and also fixed intial level of lint errors #25280

### LINKED ISSUE #25280: test: Fix make jslint to include test scripts too.
Lint doesn't run on test scripts and errors are caught at later stage during code review.

We should fix ```make jshint``` to include test scripts too.

### PR DESCRIPTION
**Pull request by saquibkhan**
test:lint Lint added for test folder and also fixed intial level of lint errors

Added closure linter for test folder. Fixed 2k+ issues in 300 files.

Fixes #25280

### CODE REVIEW

**Comment by saquibkhan** [comment]
@misterdjules thanks for the comment. I have updated the code accordingly.

**Comment by misterdjules** [comment]
@joyent/node-coreteam Now that I'm thinking about it, I would actually advocate for landing that in v0.12. If we land this in master, it's going to be painful when we merge changes in tests from v0.12 to master because the two will have diverged significantly. It would probably not require any change to this PR since master and v0.12 are probably identical currently.

**Comment by saquibkhan** [comment]
@misterdjules Done!

**Comment by misterdjules** [comment]
@saquibkhan Thanks, let's wait for @joyent/node-coreteam to give us some feedback on [my proposal for landing this in v0.12 instead of master](https://github.com/joyent/node/pull/25288#issuecomment-101747184), and then we'll do a thorough code review (although at first sight changes look good).

Thank you once again! :+1:

**Comment by cjihrig** [comment]
@misterdjules yes, 0.12 makes more sense since there should be no behavior change.

**Comment by jasnell** [comment]
@misterdjules @cjihrig ... what would you like to do with this one?

**Comment by cjihrig** [comment]
The converged repo uses ESLint. I don't personally see a need for this, but others might.

**Comment by jasnell** [comment]
Hmm.. I'm inclined to close. If someone wanted to do this in v0.12 a new PR can be opened

**Comment by jasnell** [comment]
Closing this one here. Can revisit if necessary but it's not likely to land.

**Pull request closed without merging**
