### PR TITLE
https: fix agent servername option

### PR DESCRIPTION
**Pull request by skenqbx**
Original Issue: https://github.com/iojs/io.js/issues/1106
Reference PR: https://github.com/iojs/io.js/pull/1110

### CODE REVIEW

**Comment by skenqbx** [comment]
Is it possible to get this PR into the next maintenance release of node v0.10?
I would also like to port this fix to v0.12.

**Comment by skenqbx** [comment]
@misterdjules Can I do anything to move this forward?

**Comment by ownagedj** [comment]
Plus one! Please merge

**Comment by achselschweisz** [comment]
+1

**Comment by jasnell** [comment]
LGTM

**Comment by jasnell** [comment]
Landed in 75c84b2 and 572663f

**Pull request closed without merging**
