### PR TITLE
correct example code

### PR DESCRIPTION
**Pull request by AlexKVal**

### CODE REVIEW

**Comment by misterdjules** [comment]
Thanks @AlexKVal for your contribution! The sample code describes the normal usage of `stream.Writable.end()`, so I don't think we want it to trigger an error.

However I agree that it's slightly confusing since the example is right after the sentence `Calling write() after calling end() will raise an error.`.

Maybe we could have the normal use case sample code before that sentence, and have a specific code sample for the write-after-end error after that sentence?

What do you think?

**Comment by AlexKVal** [comment]
Agree. I had written it without thinking some steps ahead.

Something like this ?

>The right way:
`right example code`

>The wrong way:
`wrong example code`

**Comment by misterdjules** [comment]
@AlexKVal Right, something like:
```
Call this method when no more data will be written to the stream. If supplied, the callback is attached as a listener on the finish event.

// write 'hello, ' and then end with 'world!'
var file = fs.createWriteStream('example.txt');
file.write('hello, ');
file.end('world!');

Calling write() after calling end() will raise an error:

// end with 'world!' and then write with 'hello, ' will raise an error
var file = fs.createWriteStream('example.txt');
file.end('world!');
file.write('hello, ');
```

**Comment by AlexKVal** [comment]
I'm closing this PR because of #15517.

**Pull request closed without merging**
