### PR TITLE
timer: call list.start regardless new or not

### PR DESCRIPTION
**Pull request by abbr**
Call start regardless whether list is new
or not to prevent incorrect active_handles
count.

Fixes issue #25831.

### CODE REVIEW

**Comment by garrettsickles** [comment]
What a great fix! This should be included asap!

**Comment by snuggles08** [comment]
+1

**Comment by misterdjules** [comment]
To paraphrase my comment in #25831:

> While `deasync` seems to rely too much on Node.js' internals, the fix suggested in [this PR] actually looks good to me so far, and thus I think I would be inclined to merge it in.

**Comment by jasnell** [comment]
This looks good but would you be able to include a test case for it?

**Comment by abbr** [comment]
@jasnell,  a test case would require either writing a c++ module or obtaining `deasync` via npm. I cannot find any existing cases under `test/simple` setup this way. In `test/addons` there are test cases written in c++ but that folder doesn't seem to be included in `make test`. Do you have any suggestion where to put the test case?

**Comment by jonathanleang** [comment]
:+1:

**Comment by jonathanleang** [comment]
:shipit:

**Comment by thefourtheye** [comment]
cc @Fishrock123

**Comment by vkurchatkin** [comment]
If it's impossible to write a test without external dependencies, then it's not a bug

**Comment by Fishrock123** [comment]
I think this is a bug. My tired self does not think that the proposed patch could actually fix this. We'll see tomorrow maybe.

**Comment by abbr** [comment]
I have added a test case, without any dependencies. Confirmed test case caused existing version 0.12.7 hung but passed with the fix.

**Comment by Fishrock123** [comment]
@abbr could we move this issue to https://github.com/nodejs/node? I'd prefer to review it there.

**Comment by vkurchatkin** [comment]
@Fishrock123 so what's the bug? running `uv_run` is clearly not supported so it should be something else

**Comment by abbr** [comment]
@Fishrock123, I have ported this pr to https://github.com/nodejs/node/pull/2788

**Comment by ChALkeR** [comment]
Closing here.

**Pull request closed without merging**
