### PR TITLE
http: avoid create new socket

### PR DESCRIPTION
**Pull request by fengmk2**
when active sockets reach max sockets limit

### CODE REVIEW

**Comment by JacksonTian** [comment]
提到 v0.12 分支比较好

**Comment by fengmk2** [comment]
@JacksonTian what's the different?

**Comment by JacksonTian** [comment]
v0.12上的发布了之后才会merge到master上来。

**Comment by fengmk2** [comment]
Merge in iojs

**Comment by jasnell** [comment]
Appears to already have landed in nodejs/node. Closing here. Can reopen if necessary

**Pull request closed without merging**
