### PR TITLE
openssl: arm64 compile fix

### PR DESCRIPTION
**Pull request by obastemur**
Compiling openssl was failing on arm64 platform.

### CODE REVIEW

**Comment by jasnell** [comment]
Given that this changes openssl, wouldn't it be better to patch this upstream? Is this error specific to node's use of openssl or a general problem with openssl?

**Comment by obastemur** [comment]
AFAIK this config file is customized anyways.

**Comment by jasnell** [comment]
@shigeki ... would you be able to take a look at this when you've got a moment?

**Comment by shigeki** [comment]
I don't think node-v0.12.x supports arm64 yet and adding a support of a new arch to node-v0.12 is not a good idea to me. 
````
  --dest-cpu=DEST_CPU   CPU architecture to build for. Valid values are: arm,
                        ia32, x64
````

**Comment by jasnell** [comment]
@shigeki .. good point :-) @obastemur ... I'm going to close this here specifically because arm64 is not supported but I would encourage you to please make sure this is working in io.js. If it's not, then we'll want to get the fix in there. Would you be able to open this against io.js if necessary?

**Comment by obastemur** [comment]
> I would encourage you to please make sure this is working in io.js. If it's not, then we'll want to get the fix in there. Would you be able to open this against io.js if necessary?

@jasnell sure.

**Pull request closed without merging**
