### PR TITLE
zlib: add adler32 and crc32

### PR DESCRIPTION
**Pull request by seishun**
Continuing from #7213.

I couldn't think of a way to make a streaming interface without over-complicating the API, and it seems like something that could be easily implemented by a user-land library. But if someone can do some benchmarking and show that marshaling the running checksum between JS and C++ causes a significant performance loss, it will be a good reason to reconsider.

The proposed API is pretty straightforward. If it LGTY, I'll add docs and tests.

### CODE REVIEW

**Comment by jasnell** [comment]
@indutny @chrisdickinson @trevnorris ... unfortunately this one seems to have stalled out. Any further thoughts on this one?

**Comment by JavaScriptDude** [comment]
Sure would be great to see some cpu efficient checksum tools in the node.js base for those non-crypto usecases like file change checking algorithms.

**Comment by jasnell** [comment]
@JavaScriptDude ... I agree. At this point tho, I'm just trying to get a sense of where it should land. It's probably not something we'd add to v0.12 at this point so I'm thinking this should be closed here and reopened against the active development stream at http://github.com/nodejs/node

**Comment by jasnell** [comment]
Going to close this here. The PR would never be able to land in it's current state and an updated PR opened against http://github.com/nodejs/node master would be needed. That's not to comment on the validity of this.

**Comment by JavaScriptDude** [comment]
For the record, I have added a new issue to open a discussion to [Incorporate suite of hash utilities into node #2444](https://github.com/nodejs/node/issues/2444)

**Pull request closed without merging**
