### PR TITLE
module: fix addition of filetypes, if require ends with ..

### PR DESCRIPTION
**Pull request by robertkowalski**
Given my home-directory is `/Users/rocko` - and I have a file named
`npm.json` in it and also a repository with name `npm`, which is a
node-module.

When try to require the `/Users/rocko/npm/index.js` two direcotry
levels down in the npm folder (e.g. `/Users/rocko/npm/test/tap`)
with `require("../../")` node will load `/Users/rocko/npm/index.js`.

When I use `require("../..")` node will load `/Users/rocko/npm.json`
which is fixed by this commit.

### CODE REVIEW

**Comment by jasnell** [comment]
@robertkowalski ... still need/want this?

**Comment by robertkowalski** [comment]
it landed in io.js along with other improvements to the module loader

**Comment by jasnell** [comment]
Do you see a reason to land it in v0.12? Or can we close this and pick it up under the converged stream?

**Comment by robertkowalski** [comment]
it is a bugfix, but a breaking fix. the idea was to land it in 0.11 and get it into the 0.12 release. i am happy if it lands in the next versions, so we can close it. :)

**Pull request closed without merging**
