### PR TITLE
build: Intl: bump ICU4C from 54 to 55

### PR DESCRIPTION
**Pull request by srl295**
Fixes: #25855 
node was using ICU4C 54 ( released 2014-oct-06 )
- Bump to ICU4C 55 ( released 2015-apr-08)
  - Timezone fixes, translation fixes, bug/performance fixes.
  - Speed improvements in date formatting
  - ICU4C 55 changelog: http://site.icu-project.org/download/55
  - CLDR 27 changelog: http://cldr.unicode.org/index/downloads/cldr-27
- Retarget the file exclusions from ICU4C 54 to ICU4C 55
  - (improves on-disk footprint on some platforms)

Originally-Fixes: https://github.com/nodejs/node/issues/2292
Original-PR-URL: https://github.com/nodejs/node/pull/2293

@orangemocha @joaocgreis or anyone any comments on the rebase?

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM!

**Comment by joaocgreis** [comment]
LGTM, but the PR-URL is corrupted. It can be simply removed, will be added by Jenkins and would get duplicated.

**Comment by srl295** [comment]
@joaocgreis it's just a placeholder (hash snowman), I didn't have a PR # when it landed. I've fixed this in d9eedaf

**Comment by joaocgreis** [comment]
@srl295 Unless you plan to land this manually, only the `Fixes:` line is needed. Jenkins will add the `PR-URL` and `Reviewed-By` lines.

**Comment by srl295** [comment]
@joaocgreis ok… I was going to land it manually, but I don't have to. I removed all but `Fixes:`. What's next?

**Comment by joaocgreis** [comment]
That's it! LGTM. Now just go to https://jenkins-iojs.nodesource.com/job/node-accept-pull-request/ , start a new build with parameters, fill the PR_ID and REVIEWED_BY fields. Note that apply changes is on by default. When it's done, close this with `Landed in ####.` and the issue with `Fixed by ####.`, with the final commit hash. I can take care of this if you want :)

**Comment by srl295** [comment]
@joaocgreis thanks. I requested access, probably better to learn it.

**Comment by orangemocha** [comment]
@srl295 I had sent you an email with your Jenkins account info a few weeks back. Now I resent it. Let me know if you didn't get it.

**Comment by srl295** [comment]
OK, the build is off and running, thanks all.

**Comment by joaocgreis** [comment]
@srl295 The SmartOS machines were broken for a few hours, my fault, and the CI job failed, sorry. I started it again, exactly the same parameters: https://jenkins-iojs.nodesource.com/job/node-accept-pull-request/29/

**Comment by srl295** [comment]
@joaocgreis +1 - at least I found the right button!

**Comment by joaocgreis** [comment]
Landed in 15030f26fdc1f1024748eceaf75eccfb650c9b9c.

@srl295 All done, thanks!

**Pull request closed without merging**
