### PR TITLE
url: resolve urls with . and ..

### LINKED ISSUE #8992: url resolve(href, '.') sometimes leaves off trailing slash
The following script:

    var url = require('url');
    console.log(url.resolve('http://www.example.com/path/to/edit', 'view'));
    console.log(url.resolve('/path/to/edit', 'view'));
    console.log(url.resolve('http://www.example.com/path/to/edit', '.'));
    console.log(url.resolve('/path/to/edit', '.'));

produces the following output:

    http://www.example.com/path/to/view
    /path/to/view
    http://www.example.com/path/to/
    /path/to

which is: resolving '.' produces a result that contains a trailing slash if the base url is absolute including host, but leaves it off if there is no host name (AKA "relative to the domain root").

These are very different urls both for a webserver and as a base url for a browser.

On every browser I have tested, using the following html

    <html>
    <head>
    <base href="/path/to/edit" />
    </head>
    <body>
    <a href="." onclick="alert(this.href); return false">test</a>
    </body>
    </html>

the href of the test link also always includes the slash.

Tested with v0.10.35

### PR DESCRIPTION
**Pull request by misterdjules**
'.' and '..' are directory specs and resolving urls with or without the
hostname with '.' and '..' should add a trailing slash to the end of the
url.

Fixes #8992.

### CODE REVIEW

**Comment by misterdjules** [comment]
@trevnorris @cjihrig After merging v0.10 into v0.12 and v0.12 in master, the [revert])(https://github.com/joyent/node/pull/9257) of the [original PR](https://github.com/joyent/node/pull/9010) has landed into v0.12 and master.

According to my [comment](https://github.com/joyent/node/pull/9257#issuecomment-76500324) a while ago, I suggest landing the [original PR](https://github.com/joyent/node/pull/9010) in master, which is why this PR is created against master.

**Comment by trevnorris** [comment]
SGTM.

**Comment by cjihrig** [comment]
Works for me too. LGTM

**Comment by misterdjules** [comment]
@amir-s @trevnorris @cjihrig Thank you! Finally landed for good in 9b534e2 :+1:

**Pull request closed without merging**
