### PR TITLE
deps: update to openssl-1.0.1m 

### PR DESCRIPTION
**Pull request by jasnell**
The commits are split out the same way as in @shigeki's io.js commit (https://github.com/iojs/io.js/pull/1206). The end result is identical to the previous PR.

### CODE REVIEW

**Comment by misterdjules** [comment]
@jasnell @indutny Out of curiosity, what problem does https://github.com/jasnell/node/commit/7817fbd692120887619d07228882dd19461109b6 solve? I don't see any assembly file changed in this PR, and unless I'm missing something the perl script is not run when OpenSSL is built in node's tree. Also, building node with `vcbuild ia32 nosign` on Windows does not give me any build error.

**Comment by misterdjules** [comment]
@jasnell Ran `test/external/ssl-options` and all tests pass. Except for my question [in the previous comment](https://github.com/joyent/node/pull/9451#issuecomment-84748349), LGTM.

Thank you all @jasnell, @shigeki and @indutny.

**Comment by indutny** [comment]
@misterdjules auto-generated assembly contains this on a newer OpenSSL. Basically, it'll fail to build with `.486`.

**Comment by misterdjules** [comment]
@indutny By "newer OpenSSL", do you mean other versions than 1.0.1m? Also, like I said in my previous comment node builds without any problem for me on Windows for ia32 with `.486`, hence my questions.

**Comment by misterdjules** [comment]
@indutny Ok, just realized that it's another old floating patch, and that it'll have an impact if any asm file needs to be (re)generated on Windows, which has not been the case for this upgrade. Sorry for the confusion.

**Comment by misterdjules** [comment]
LGTM.

**Comment by misterdjules** [comment]
@joyent/node-coreteam Landing and doing a release asap.

**Comment by misterdjules** [comment]
No regression [on UNIX](http://jenkins.nodejs.org/job/node-review-unix-julien/48/) nor [on Windows](http://jenkins.nodejs.org/job/node-review-windows-julien/40/).

**Comment by misterdjules** [comment]
Landed in c6e8a2c920e0cecebfb8fe62d5bcfc19edb850ae, 10717f659b1d8db86cc7fce6f6a64e4c0ba22062, 2b21c45f75043f8e5728650e24a4e972ade18cf1, 63377ec3c3ed52d7dec04515854a760787b9893f, 15cdeb7d990d278f569ba0733bf6feec97916cc6,  1fc3fdf8925d4bfd2aaead48885a5f0b77607f77 and 4b69c72b8b1725fe98539da1274bc85d3661d3a5.

**Pull request closed without merging**
