### PR TITLE
fs: Fix StatWatcher to handle error codes passed in status

### LINKED ISSUE #25345: fs.watchFile regression in 0.12
When `fs.watchFile(path, callback)` is called on an non-existing file, the `0.12` behavior is different than `0.10`.

In `0.10.38`, the callback is never called.

In `0.12.2`, the callback is called immediately with this object as `curr` and `prev`:
```js
{ dev: 0,
  mode: 0,
  nlink: 0,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 0,
  ino: 0,
  size: 0,
  blocks: 0,
  atime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  mtime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  ctime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  birthtime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET) }
```

This new behavior breaks one of my scripts.

### PR DESCRIPTION
**Pull request by dnakamura**
fixes #25345

### CODE REVIEW

**Comment by cjihrig** [comment]
Can you add a test?

**Comment by dnakamura** [comment]
@cjihrig  Tests are added, can you take a look?

**Comment by cjihrig** [comment]
It looks like io.js started to go down this path in https://github.com/nodejs/io.js/pull/2028, but decided against it. The current proposed fix is in https://github.com/nodejs/io.js/pull/2093. I think we should try to stay consistent with io.js in this case.

**Comment by thefourtheye** [comment]
@cjihrig Strictly speaking, https://github.com/nodejs/io.js/pull/2093/ is not a fix for this, it simply makes this as a documented feature :-)

**Pull request closed without merging**
