### PR TITLE
net: throw on write after close

### PR DESCRIPTION
**Pull request by juliangruber**
`socket.write()` on a closed socket will either throw or pass an error to the callback.

see https://github.com/joyent/node/pull/7623#issuecomment-43895947

### CODE REVIEW

**Comment by juliangruber** [comment]
any updates?

**Comment by jasnell** [comment]
@chrisdickinson @indutny .. any further thoughts on this one?

**Comment by indutny** [comment]
I'm not sure how well it plays with the streams API that we are exposing now. Probably not that well at all (take a look at `pipe` implementation)

**Comment by jasnell** [comment]
Ok. @juliangruber , given how things have evolved in the streams API, this would need to be revisited if it's still an issue you want to pursue. The right place would be either at http://github.com/nodejs/node or http://github.com/nodejs/readable-stream. Closing this here.

**Pull request closed without merging**
