### PR TITLE
build: fix VS2015 ICU/Intl breakage <56 (v0.12)

### LINKED ISSUE #25792: build: VS2015 failure (ICU) back port from io.js
https://github.com/nodejs/io.js/issues/2279 will affect 0.12+ as well under VS2015 with `Intl` on.

Basically, VS2015 broke ICU. We'll fix it in ICU 56.

It should apply cleanly, but I couldn't get VS2015 to build with `joyent/node/master`.

I will open a PR anyway, but will need some help testing.

NB this also adds a general mechanism for floating patches on top of ICU.
@orangemocha

### PR DESCRIPTION
**Pull request by srl295**
rebased to v0.12

probably fixes #25792

Also, adds general mechanism for floating patches on top of ICU.

The particular ufile.c is from
 http://bugs.icu-project.org/trac/changeset/37704
and should be OK for ICU 54 and 55.

backport from: https://github.com/nodejs/io.js/pull/2283
- includes responses to comments in from io.js version
- also apply patch to ICU 55 (if/when that is merged)

### CODE REVIEW

**Comment by srl295** [comment]
@orangemocha

**Comment by srl295** [comment]
As of 3e46d6dc86ccd184a1dd49328ed4192e8050f762 this is parallel to the io.js side

**Comment by srl295** [comment]
@joaocgreis do you want to take this as part of your work?

**Comment by joaocgreis** [comment]
@srl295 I've just submitted this: https://github.com/joyent/node/pull/25857 , enabling VS2015 in v0.10. When it lands, the plan is to merge v0.10 into v0.12. It would be nice to have this already landed, and VS2015 support would be complete. So, LGTM!

**Comment by joaocgreis** [comment]
@srl295 I think it would be good to reorganize the commit message, and then I can take care of landing this. There is no official guide for commit messages for ports that I know of, so I've been adapting the [one specific for v8](https://github.com/joyent/node/wiki/V8-upgrade-process#cherry-picking-commits-from-v8s-github-mirror). I would amend the commit message to something like:

```
build: work around VS2015 issue in ICU <56

This change is a backport of
nodejs/node@4c06515a2f13c9b0890b374bb3ab3c0740c282e2.

Original commit message:

  The particular ufile.c is from
  http://bugs.icu-project.org/trac/changeset/37704
  and should be OK for ICU 54 and 55.

  Also, adds general mechanism for floating patches on top of ICU.

  Fixes: nodejs/node#2279
  PR-URL: nodejs/node#2283
  Reviewed-By: João Reis <reis@janeasystems.com>

Fixes: #25792
```

Feel free to change/add anything in my suggestion. If you're ok with it as it is, I can also take care of this and land, let me know.

**Comment by srl295** [comment]
@joaocgreis the message looks good to me.

**Comment by joaocgreis** [comment]
CI: https://jenkins-iojs.nodesource.com/job/node-test-commit/281/

Landed in 4f2456369c80ae940fb654e16afda15b9bb4a349.

Thank you!

**Pull request closed without merging**
