### PR TITLE
add ability to add more stdio channels in child_process.fork and cluster.fork

### PR DESCRIPTION
**Pull request by EugenDueck**
Export ability (partly) of `child_process.spawn()` to specify fds / channels between parent and child to `child_process.fork()` and `cluster.fork()`, in reference to issue #5727

### CODE REVIEW

**Comment by moll** [comment]
Is this issue still alive? I've got the same wish to set fork options when spawning new cluster workers.

**Comment by sam-github** [comment]
Why was env made mandatory? Seems a pointless incompatibility which will break almost all uses of cluster.

**Comment by moll** [comment]
Perhaps we're back to needing a user-space implementation of Cluster? The Cluster module could provide a few primitives, but that way the whole connection scheduling et al. features could be improved upon more frequently.

**Comment by EugenDueck** [comment]
@sam-github Fair enough point. In actual fact, `env` is only mandatory (but can be null) when `options` is provided. But if env is not provided, behavior has not changed. Not sure how to document this. It's like two method overloads.

```
cluster.fork([env]) // overload 1
  ...
cluster.fork(env, options) // overload 2
  ...
```

**Comment by sam-github** [comment]
@EugenDueck 

`cluster.fork([env[, options]])`

**Comment by jasnell** [comment]
@EugenDueck @sam-github ... given that this is targeted at master and has conflicts, if this is still something that should land, it needs to be updated and reopened against nodejs/node. Recommend closing this here.

**Comment by jasnell** [comment]
Closing this here. @EugenDueck, if you'd like to pursue this API change, please update and open a new PR against http://github.com/nodejs/node master. Thank you!

**Pull request closed without merging**
