### PR TITLE
configure changes for portability and better interop

### PR DESCRIPTION
**Pull request by ensonic**
We are using these two changes for the chromeos packages of nodejs to make the build work in a cross compilation environment with custom toolchains.

### CODE REVIEW

**Comment by jasnell** [comment]
@ensonic ... at this point, because of the transition over to http://github.com/nodejs/node, it would likely be best to retarget this at nodejs/node or open a discussion at nodejs/build.

**Comment by ensonic** [comment]
Hmm, I don't get it. This PR is for nodejs/node. Atleast when I opened the PR.

**Comment by jasnell** [comment]
The PR was opened originally against the joyent/node repo, which is now archived. We would need this opened against the new nodejs/node repo

**Comment by ensonic** [comment]
+jasnell, not your fault, but honestly this sucks. This is a not a great way to attract new contributors. The patches don't apply to upstream anymore and from cursory checking, they won't be needed anymore. At least I can't see any compiler version checks in the handrolled (yeah) configure script. And pkgconfig is resolved via the envvar too.

**Pull request closed without merging**
