### PR TITLE
debugger: also exit when the repl emits 'exit'

### LINKED ISSUE #5631: Repl in node debug can only be exited using ctrl-c
Node debug allows you to drop into a repl at your current location using the `repl` command. To exit this, the only allowed method is to use `ctrl-c` since `.exit` does not work. As shown [here](https://github.com/joyent/node/blob/master/lib/_debugger.js#L1545), the repl listens to SIGINT, but sending it a sigint with kill, breaks the debugger. 

I'm not sure, but [digging into the repl source](https://github.com/joyent/node/blob/master/lib/repl.js#L169) seems to indicate that it only pays attention to SIGINT from the attached terminal, instead of in general. This is a problem if the debugger is a child process of a script, and SIGINT on the script causes an exit.

If `.exit` acted the same as `ctrl-c` during debugging, this problem would be solved.

### PR DESCRIPTION
**Pull request by fb55**
Fixes #5631

### CODE REVIEW

**Comment by jasnell** [comment]
@cjihrig ... this is targeted at master. Do we want to push this off to nodejs/node or get this landed in v0.12?

**Comment by cjihrig** [comment]
@jasnell let's take it to nodejs/node.

**Comment by jasnell** [comment]
@fb55... I know it's been a while, but are you willing to update this and open it against master in http://github.com/nodejs/node?

**Comment by fb55** [comment]
@jasnell /done

**Comment by jasnell** [comment]
Thanks!

**Pull request closed without merging**
