### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM

**Comment by jasnell** [comment]
I notice that the typo also exists in v0.12 and v0.10 branches. Given that it's such a minor thing tho, I'm just going to land this against master and v0.12 and leave the v0.10 one alone.

**Comment by jasnell** [comment]
Landed in #be7eb83

**Comment by radarhere** [comment]
Thanks!

**Pull request closed without merging**
