### PR TITLE
Adding a simple stream.Duplex example

### PR DESCRIPTION
**Pull request by jasnell**
Per issue #8776, adding a simple example of a stream.Duplex implementation to the docs. The example duplex is admittedly limited in function but it illustrates the key bits.

### CODE REVIEW

**Comment by jasnell** [comment]
@joyent/node-tsc @trevnorris  ... can someone give this a quick review?

**Comment by trevnorris** [comment]
I don't understand why the usage of nextTick?

**Comment by jasnell** [comment]
honestly, I don't remember... I wrote that very quickly back in december and do not remember much of the detail ;-) ... the entire example could likely be simplified.

**Comment by trevnorris** [comment]
Let's do that. I'll be happy to help if needed. Have flashbacks about "basic"  implementation examples when I first started and thinking, "wtf have I gotten myself into?"

**Comment by jasnell** [comment]
Will reopen against nodejs/node...

**Pull request closed without merging**
