### PR TITLE
Defragment & Prepare 1.0.0

### PR DESCRIPTION
**Pull request by phpnode**
With 0.12.0 finally out the door, it's time for the first ever production ready version of node, 1.0.0! 

This PR resolves that fragmentation issue people keep talking about (I couldn't find an open ticket for it, sorry), also fixes many V8 bugs and enables generators by default.

### CODE REVIEW

**Comment by petkaantonov** [comment]
+1

**Comment by despairblue** [comment]
:+1:

**Comment by cjihrig** [comment]
What exactly is this? I'm assuming a merge from io.js. Seems like a lot of stuff is still missing (I didn't look at all the changes, but it's only 68 commits). How does it address the different dependency versions and the changes in the io.js test directory?

**Comment by phpnode** [comment]
@cjihrig yes it's a merge from latest io.js master, it's obviously not ready to be merged yet, I just wanted to get the ball rolling since joyent now seem more interested in reconciliation.

**Comment by Globegitter** [comment]
:+1:

**Comment by Fishrock123** [comment]
@phpnode the commits are at v1.x, not master. :)

**Comment by misterdjules** [comment]
There are certainly a lot of good changes in this PR (and in the io.js repository in general) that we want to integrate at least at some point in the future.

However, instead of submitting one PR with a large number of commits, I would suggest to submit PRs with well identified atomic changes that we can review, test and integrate correctly according to our current contribution process.

Closing this issue, but any PR with a better defined scope that would port changes from io.js and would improve the quality of this repository is more than welcome.

Thank you!

**Pull request closed without merging**
