### PR TITLE
Intl: Automatically download ICU if requested. Reduce size. Keep `--with-intl=none` the default. 

### PR DESCRIPTION
**Pull request by srl295**
Background: see joyent#7676 of course
- [x] decide which variant is on by default
- [x] make it on by default
- [x] test more failure cases of downloading
- [x] add md5 sum
- [x] test more platforms

### CODE REVIEW

**Comment by srl295** [comment]
No problem, happy new year and ping?

**Comment by srl295** [comment]
ping @trevnorris
>
>

**Comment by trevnorris** [comment]
@srl295 Thanks. Been testing it out and works great. One question on usability. Do you think `make clean` should cleanup the icu data?

**Comment by srl295** [comment]
@trevnorris 98287929349b80390af337a8a76fac98cf82e58e causes `make distclean` to cleanup `deps/icu*` and `icu_config.gypi`

**Comment by trevnorris** [comment]
Thanks much. Squashed and landed in a30839576c.

**Pull request closed without merging**
