### PR TITLE
implement domain-like hooks (asynclistener) for userland

### PR DESCRIPTION
**Pull request by trevnorris**
Here's the current API planned for implementation:

``` javascript
// Class that will store information about a specific request.
function Storage() { }

// This will be called every time asynchronous work is queued.
// The returned data will propagate to the callbackObject's callbacks.
function onCreation() {
  return new Storage();
}

// Set of methods that will run at specific points in time according to
// their cooresponding callbacks. These methods are always run FIFO if
// multiple are queued.
// "context" is the "this" of the request object.
var callbackObject = {
  before: function asyncBefore(context, storageValue) {
  },
  // "returnValue" is the value returned from the callback.
  after: function asyncAfter(context, storageValue) {
  },
  // If this callback returns "true" then the error handler will assume
  // the error was properly handled, and process will continue normally.
  // If multiple error handlers are queued, and any one of those returns
  // true, then Node will assume the error was properly handled.
  // This will not currently be passed the context (or "this") of the
  // callback that threw. A simple way of achieving this is currently
  // being investigated, and the feature will be added when one is found.
  error: function asyncError(storageValue, err) {
  }
};

/**
 * process.addAsyncListener(callback[, object[, value]]);
 *
 * Arguments:
 *
 * callback - Function that will be run when an asynchronous job is
 *    queued.
 *
 * object - Object with the optional callbacks set on:
 *    before - Callback called just before the asynchronous callback
 *        will be called.
 *    after - Callback called directly after the asynchronous callback.
 *    error - Callback called if there was an error.
 *
 * The returned key is an Object that serves as the unique key for the
 * call (much like how Timers work).
 */
var key = process.addAsyncListener(onAsync, callbackObject);


/**
 * process.createAsyncListener(callback[, object[, value]]);
 *
 * Adding an async listener will immediately add it to the queue and
 * being listening for events. If you wish to create the listener in
 * advance, to say attach to the returned value object, it's possible
 * to get the key and pass it to process.addAsyncListener() later.
 */
var key = process.createAsyncListener(onAsync, callbackObject, value);

// Then activate like so:
process.addAsyncListener(key);


/**
 * process.removeAsyncListener(key);
 *
 * Remove any async listeners and associated callbackObjects. All
 * listeners will live independent of each other, and there will be no
 * method given to clear all async listeners.
 */
process.removeAsyncListener(key);
```

### CODE REVIEW

**Comment by RobinQu** [comment]
Is it landed on any released version? 
I still cannot find it in the latest(v0.12.2)

**Comment by trevnorris** [comment]
@RobinQu Never landed.

**Comment by gobwas** [comment]
So, will node have this feature some day?

**Comment by trevnorris** [comment]
@gobwas It partially exists as `process.binding('async_wrap')`. Though the ability to capture exceptions was removed. Became a massive hair ball. Would still like to do this, but time constraints.

**Comment by gobwas** [comment]
Thank you, @trevnorris!

Does this feature present in iojs docs? 

Any way, I am asking about [async-listener](https://www.npmjs.com/package/async-listener) functionality at the moment..?

**Comment by trevnorris** [comment]
Oh, that died a horrible death. After 3 months of work I still couldn't figure out a few key edge cases. So instead I've been working on the set of hooks necessary to implement a feature like async-listener. This way others can experiment and publish their own modules.

**Comment by gergelyke** [comment]
Hi @trevnorris ,

could you give us an update on the current status of this? What would be your suggestion to use these days if we want to active the same functionality? 

Thanks!

cc @peteyy

**Comment by trevnorris** [comment]
@gergelyke Unfortunately there isn't an alternative. Will have to continue using domains for the time being. Though discussion about reimplementing this has started back up. Hopefully it will lead to something.

**Comment by gergelyke** [comment]
thanks!

**Comment by naorye** [comment]
What is wrong with the Domain solution?

**Comment by trevnorris** [comment]
@naorye It's a complete hack that injects itself all over core code. By design it can't properly catch everything. There are edge cases it's missing. This is because it's injected at the JS API level, not at the native level where the asynchronous requests are actually made.

**Comment by Olegas** [comment]
What alternatives are now being discussed?

**Comment by jiaqifeng** [comment]
@trevnorris Is there any other solutions based on native layer of this problem currently available? I am a Java coder, I think if this should be done on VM layer which make things easier and more efficient.

**Comment by trevnorris** [comment]
@jiaqifeng In master there's a native API that can be used (see all functions that use `async_context` in [node.h](https://github.com/nodejs/node/blob/master/src/node.h)). This will be backported to v8.x, but no further.

**Pull request closed without merging**
